// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNpVKpi7ENu6qKj4G99EcvFP5xDrNQ2o',
    appId: '1:856981693621:web:665fc9c453681d774b8afc',
    messagingSenderId: '856981693621',
    projectId: 'suheda-ab999',
    authDomain: 'suheda-ab999.firebaseapp.com',
    storageBucket: 'suheda-ab999.firebasestorage.app',
    measurementId: 'G-JR1GCJC1SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv5y8ynqiWCwFnPfEqmwX1_C3WJmLq2P8',
    appId: '1:856981693621:android:d62f1a97c8751d254b8afc',
    messagingSenderId: '856981693621',
    projectId: 'suheda-ab999',
    storageBucket: 'suheda-ab999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDdcNYRrL80Li42QrqzP9aWSk0MYnFZ0',
    appId: '1:856981693621:ios:dc508c141d4a1f1f4b8afc',
    messagingSenderId: '856981693621',
    projectId: 'suheda-ab999',
    storageBucket: 'suheda-ab999.firebasestorage.app',
    iosBundleId: 'com.example.tutordesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXDdcNYRrL80Li42QrqzP9aWSk0MYnFZ0',
    appId: '1:856981693621:ios:dc508c141d4a1f1f4b8afc',
    messagingSenderId: '856981693621',
    projectId: 'suheda-ab999',
    storageBucket: 'suheda-ab999.firebasestorage.app',
    iosBundleId: 'com.example.tutordesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLNpVKpi7ENu6qKj4G99EcvFP5xDrNQ2o',
    appId: '1:856981693621:web:9b3a669fbbfe0bc94b8afc',
    messagingSenderId: '856981693621',
    projectId: 'suheda-ab999',
    authDomain: 'suheda-ab999.firebaseapp.com',
    storageBucket: 'suheda-ab999.firebasestorage.app',
    measurementId: 'G-1XY1TJE3D3',
  );
}
